const data = [
    { name: 'Maryland', parent: '', amount: 6018848 },
    { name: 'Montgomery County', parent: 'Maryland', amount: 1043530 },
    { name: 'Prince Georges County', parent: 'Maryland', amount: 908670 },
    { name: 'Baltimore City', parent: 'Maryland', amount: 828018 },
    { name: 'Baltimore County', parent: 'Maryland', amount: 609032 },
    { name: 'Anne Arundel County', parent: 'Maryland', amount: 571275 },
    { name: 'Howard County', parent: 'Maryland', amount: 318855 },
    { name: 'Harford County', parent: 'Maryland', marylandamount: 252222 },
    { name: 'Frederick County', parent: 'Maryland', amount: 251422 },
    { name: 'Carroll County', parent: 'Maryland', amount: 167699 },
    { name: 'Charles County', parent: 'Maryland', amount: 159428 },
    { name: 'Washington County', parent: 'Maryland', amount: 150109 },
    { name: 'St. Marys County', parent: 'Maryland', amount: 112290 },
    { name: 'Cecil County', parent: 'Maryland', amount: 102552 },
    { name: 'Wicomico County', parent: 'Maryland', amount: 102539 },
    { name: 'Calvert County', parent: 'Maryland', amount: 91511 },
    { name: 'Allegany County', parent: 'Maryland', amount: 71445 },
    { name: 'Worchester County', parent: 'Maryland', amount: 51765 },    
    { name: 'Queen Annes County', parent: 'Maryland', amount: 49632 },
    { name: 'Talbot County', parent: 'Maryland', amount: 37167 },    
    { name: 'Caroline County', parent: 'Maryland', amount: 33049 },    
    { name: 'Dorchester County', parent: 'Maryland', amount: 32138 },
    { name: 'Garrett County', parent: 'Maryland', amount: 29235 },
    { name: 'Somerset County', parent: 'Maryland', amount: 25729 },
    { name: 'Kent County', parent: 'Maryland', amount: 19536 },
  ];
